---
name: logging_testing

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the script
        run: python3 scripts/test_script.py 2>&1
