---
name: update_on_merge

on:
  pull_request:
    branch:
      - testing/merge_on_commit_base

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: secrets.PERSONAL_ACCESS_TOKEN
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update Python base packages
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependency
        run: pip install --upgrade --requirement scripts/requirements.txt
      - name: Generate a JSON from the manually maintained YAML file
        run: python scripts/generate_json.py data/content.yml data/content.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: testing/commit_on_merge_base
          commit_message: Update JSON file
          commit_user_name: JSON Auto-Update
          add_options: "data/content.json"
